package com.project.fsn.sms.dev.business.common.codes;

public interface ExceptionMessageCode {
    // Generic util
    String PRS_NO_SUCH_METHOD_EXCEPTION = "PRS_NO_SUCH_METHOD_EXCEPTION";
    String PRS_ILLEGAL_ACCESS_EXCEPTION = "PRS_ILLEGAL_ACCESS_EXCEPTION";
    String PRS_INVOCATION_TARGET_EXCEPTION = "PRS_INVOCATION_TARGET_EXCEPTION";
    String PRS_INVOKE_ENUM_GENERAL_EXCEPTION = "PRS_INVOKE_ENUM_GENERAL_EXCEPTION";
    // AUTHENTICATION
    String AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
    String TOKEN_INVALID = "TOKEN_INVALID";
    String TOKEN_EXPIRED = "TOKEN_EXPIRED";
    String USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND";
    String USERNAME_NOT_FOUND_WITH_ID = "USERNAME_NOT_FOUND_WITH_ID";
    String USERNAME_NOT_FOUND_WITH_USERNAME = "USERNAME_NOT_FOUND_WITH_USERNAME";
    // USER_ENTITY
    String USER_ENTITY_CODE_CAN_NOT_BE_NULL = "USER_ENTITY_CODE_CAN_NOT_BE_NULL";
    String USER_ENTITY_USER_NAME_CAN_NOT_BE_LESS_THAN_TEN_AND_OVER_THAN_FIFTY_CHARACTERS = "USER_ENTITY_USER_NAME_CAN_NOT_BE_LESS_THAN_TEN_AND_OVER_THAN_FIFTY_CHARACTERS";
    String USER_ENTITY_FIRST_NAME_CAN_NOT_BE_LESS_THAN_TEN_CHARACTERS = "USER_ENTITY_FIRST_NAME_CAN_NOT_BE_LESS_THAN_TEN_CHARACTERS";
    String USER_ENTITY_LAST_NAME_CAN_NOT_BE_OVER_THAN_FIFTY_CHARACTERS = "USER_ENTITY_LAST_NAME_CAN_NOT_BE_OVER_THAN_FIFTY_CHARACTERS";
    String USER_ENTITY_EMAIL_HAS_NOT_A_VALID_FORMAT = "USER_ENTITY_EMAIL_HAS_NOT_A_VALID_FORMAT";
    //
    String IRDI_CODE_FORMAT_INVALID = "IRDI_CODE_FORMAT_INVALID";
}
